### ISSUE TITLE
Epilog removal of created dirs

### ISSUE THREAD

**Issue by maflister** [University-of-Delaware-IT-RCI/auto_tmpdir#1]
This is a great plugin! I'm testing and found that created directories are not automatically deleted as the documentation states. Also, I am not using the --no-rm-tmpdir flag. This was odd but then I noticed this [commit](https://github.com/jtfrey/auto_tmpdir/commit/ffc768219f82ada5dbbbc9c88617d7df03c1dee2). From my very limited understanding it appears that this has changed the documented behavior. Could you clarify how I can have automatic deletion of created directories?

Thanks so much!

**Comment by jtfrey** [comment]
There seems to be a race condition w.r.t. when to remove the directory — when the extern step is exiting, when the zeroeth step is exiting — without interfering with other step(s) that are still executing. E.g. if extern is exiting and we try to "rm -rf" the TMPDIR there may be files in-use that prohibit complete removal. One solution might be to have every step remove TMPDIR, but then multip-step jobs will have one step destroying TMPDIR for others.

Maintaining a reference count might be a valid approach: each job step on node X can create the TMPDIR or just increment the reference count, then each step can decrement the reference count and remove TMPDIR once the count reaches zero. But the reference count is state shared between all steps, and each step is a separate process, so there are obvious synchronization issues there, too.

**Comment by maflister** [comment]
Thanks for that explanation. If the cleanup is run at slurm_spank_job_epilog rather than slurm_spank_task_exit, would that solve the issue?

**Comment by jtfrey** [comment]
The slurm_spank_job_prolog() and slurm_spank_job_epilog() callbacks occur in a separate context — state is not shared with the other callbacks or with each other.  It makes sense to create the hierarchy in the job_script:: slurm_spank_job_prolog() context but NOT bind-mount it.  But then the remote and job_script:: slurm_spank_job_epilog() contexts are not bind-mounted and don't have the fs data already in-memory.  This implies that those other two contexts must recreate all the state (to bind-mount in the remote context and destroy the directories in the  job_script:: slurm_spank_job_epilog() context).

It's not a show-stopper to have to recreate all the state:  I've already modified the plugin on a test cluster and it seems to work okay.  But redoing auto_tmpdir_fs_init() in each context also ensures that the target directories exist and creates them if not:  it's heavier than I'd like.  Seems like one way to go would be:

1. The job_script::slurm_spank_job_prolog() context should create all the directories (not bind-mount them) and serialize the auto_tmpdir_fs_info data structure to a file.
2. The remote::slurm_spank_init_post_opt() context can attempt to restore state from the file, and if successful bind-mount everything.
3. The job_script::slurm_spank_job_epilog() context can attempt to restore state from the file, and if successful destroy the directories.

I'd have to add another config parameter, e.g. "state_dir", defaulting to /tmp and where those state files would go.  Does that sound like a valid path forward?

**Comment by jtfrey** [comment]
Please see the 0453424f0fb35a073cd9558dd762e709e7a447a5 commit to the dir-removal-fixup branch of this repository.  The refactored implementation follows the three steps mentioned above.  I've used it on my Slurm 20.02.0, CentOS 7 test cluster and it works great; let me know if the issues are resolved for you.

**Comment by maflister** [comment]
Thanks so much for these updates. My apologies for the long delay in response. 

Running Slurm 19.05.5 on CentOS 7, I get the following:
```
May 27 14:40:44 n1 spank-prolog[1199]: error: auto_tmpdir: auto_tmpdir_fs_init: unable to get job's group id
May 27 14:40:44 n1 spank-prolog[1199]: error: auto_tmpdir::slurm_spank_job_prolog: failure to create fs info
May 27 14:40:44 n1 spank-prolog[1199]: error: auto_tmpdir::auto_tmpdir_fs_serialize_to_file: failed to write fs_info->options to `/tmp/auto_tmpdir_fs-105.cache` (errno = 14)
May 27 14:40:44 n1 spank-prolog[1199]: error: auto_tmpdir::slurm_spank_job_prolog: failure to serialize fs info
May 27 14:40:44 n1 slurmd[24835]: _run_prolog: run job script took usec=10970
May 27 14:40:44 n1 slurmd[24835]: _run_prolog: prolog with lock for job 105 ran for 0 seconds
May 27 14:40:45 n1 slurmd[24835]: launch task 105.0 request from UID:20000 GID:20000 HOST:10.50.0.2 PORT:36016
May 27 14:40:45 n1 slurmstepd[1202]: error: auto_tmpdir::auto_tmpdir_fs_init_with_file: failed to read new_fs->options from `/tmp/auto_tmpdir_fs-105.cache` (errno = 0)
May 27 14:51:16 n1 spank-epilog[10115]: error: auto_tmpdir::auto_tmpdir_fs_init_with_file: failed to read new_fs->options from `/tmp/auto_tmpdir_fs-105.cache` (errno = 0)
May 27 14:51:16 n1 kernel: traps: slurmstepd[10115] general protection ip:2b4e4fc40809 sp:7ffcee4efda0 error:0 in auto_tmpdir.so[2b4e4fc3c000+7000]
May 27 14:51:16 n1 slurmd[24835]: error: spank/epilog returned status 0x008b
May 27 14:51:16 n1 slurmd[24835]: error: [job 105] epilog failed status=0:11
```

**Comment by jtfrey** [comment]
Pre 20.x releases of Slurm, the `_check_spank_item_validity()` function that checks what parameters are made available to each SPANK context (prolog/epilog as in the S_TYPE_JOB_SCRIPT context):

```
	else if (spank->stack->type == S_TYPE_JOB_SCRIPT) {
		if (item != S_JOB_UID && item != S_JOB_ID)
			return ESPANK_NOT_AVAIL;
	}
```

In the 20.x releases of Slurm, that code has changed:

```
        else if (spank->stack->type == S_TYPE_JOB_SCRIPT) {
                if (item != S_JOB_GID && item != S_JOB_UID && item != S_JOB_ID)
                        return ESPANK_NOT_AVAIL;
        }
```

So on our newest cluster (where I was developing this plugin lately) the prolog SPANK callback has access to the job's gid; on older clusters (running 18.x and 19.x) that's not the case.

So long as the directory has the correct uid ownership, it's probably not technically necessary to require that the job's gid be set on it, too.  I'll have to modify the code to either remove that entirely or make it conditional on builds against Slurm 20.x.  Thanks for reporting this.

**Comment by jtfrey** [comment]
Commit 9853882d44aa8bbb6f6b20354fbc9c9af39855b6 in the dir-removal-fixup branch has a modification to ignore the gid on the directories. Please give it a try.
