### ISSUE TITLE
CPack RPM generator

### ISSUE THREAD

**Issue by jtfrey** [University-of-Delaware-IT-RCI/auto_tmpdir#10]
Add CPack RPM generator infrastructure to the project's CMake configuration.

Initial implementation tracking in [cpack-rpm](https://github.com/University-of-Delaware-IT-RCI/auto_tmpdir/tree/cpack-rpm) branch.

**Comment by OleHolmNielsen** [comment]
The Slurm major version printed in ```cmake/slurm-version-check.c``` should have double digits such as 21.08:
```
-    printf("%d.%d.%d", \
+    printf("%2.2d.%2.2d.%d", \
```

**Comment by OleHolmNielsen** [comment]
Now the ```make package``` generates this RPM file: ```auto_tmpdir-1.0.1-21.08.8.x86_64.rpm```.

What I'm missing here is the distribution version, since we run CentOS 7.7 (el7) as well as AlmaLinux 8.6 (el8) in our cluster.

The ```slurm.spec``` file sets this:
```
Name:           slurm
Version:        21.08.8
%define rel     2
Release:        %{rel}%{?dist}
```
and thus creates RPM file names such as ```slurm-21.08.8-2.el7.x86_64.rpm```.

I found this documentation of %{?dist} https://fedoraproject.org/wiki/Packaging:DistTag

Maybe you could add the dist in the RPM file name?

**Comment by OleHolmNielsen** [comment]
The RPM package includes some /usr/lib/.build-id files which may or may not be needed:
```
drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib/.build-id
drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib/.build-id/3b
lrwxrwxrwx    1 root    root                       42 Jul  1 09:07 /usr/lib/.build-id/3b/39af89648c9715355685e31357c707e3ec571c -> ../../../../usr/lib64/slurm/auto_tmpdir.so
drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib64/slurm
-rwxr-xr-x    1 root    root                    35984 Jul  1 09:07 /usr/lib64/slurm/auto_tmpdir.so
auto_tmpdir-1.0.1-21.08.8.x86_64.rpm (END)
```
According to https://unix.stackexchange.com/questions/411727/what-is-the-purpose-of-usr-lib-build-id-dir such files are only related to debugging information.

**Comment by jtfrey** [comment]
See commit fce3e1c13102972e89a893d978c089098ca27336

**Comment by jtfrey** [comment]
> The RPM package includes some /usr/lib/.build-id files which may or may not be needed:
> 
> ```
> drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib/.build-id
> drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib/.build-id/3b
> lrwxrwxrwx    1 root    root                       42 Jul  1 09:07 /usr/lib/.build-id/3b/39af89648c9715355685e31357c707e3ec571c -> ../../../../usr/lib64/slurm/auto_tmpdir.so
> drwxr-xr-x    2 root    root                        0 Jul  1 09:07 /usr/lib64/slurm
> -rwxr-xr-x    1 root    root                    35984 Jul  1 09:07 /usr/lib64/slurm/auto_tmpdir.so
> auto_tmpdir-1.0.1-21.08.8.x86_64.rpm (END)
> ```
> 
> According to https://unix.stackexchange.com/questions/411727/what-is-the-purpose-of-usr-lib-build-id-dir such files are only related to debugging information.

That's true, and I believe it's your RPM toolchain that's doing that.  As I understand it from the cited page, the `/usr/lib/.build-id` file (= the build-id hash for `auto_tmpdir.so`) is a symbolic link to the `auto_tmpdir.so` binary in the file system.  If debug info were present, the OS could locate the original binary using that symbolic link.  The auto_tmpdir.spec file for the RPM does **not** specify the inclusion of the `/usr/lib/.build-id` files, so the RPM toolchain is doing that automatically.  As such, it should be left alone IMO.

**Comment by OleHolmNielsen** [comment]
With RHEL8 the ```/usr/lib/.build-id``` files seem to be generated by default.  A discussion is in https://unix.stackexchange.com/questions/688839/if-i-do-not-care-about-debug-support-in-red-hat-packages-what-are-the-drawbacks
It is possible to turn off this feature by adding to ```auto_tmpdir.spec``` this line:
```
%define _build_id_links none
```
The RPM file now contains:
```
Summary     : Slurm auto_tmpdir SPANK plugin
Description :
The auto_tmpdir SPANK plugin facilitates the automatic creation/removal of bind-mounted directories for Slurm jobs.
* Thu Jun 30 2022 Jeffrey Frey <frey@udel.edu> 1.0.1
- first release with RPM build capability

-rwxr-xr-x    1 root    root                    35984 Jul  4 08:10 /usr/lib64/slurm/auto_tmpdir.so
auto_tmpdir-1.0.1-21.08.8.el8.x86_64.rpm (END)
```
Note: The RPM file now contains the ```el8``` distributions, thanks a lot!

**Comment by jtfrey** [comment]
I would rather leave the `%define` as something the package maintainer can add to the spec file.  The fact of the matter is that the RPM toolset provided by the OS is adding those files *by default*.  Since that is the default behavior, I don't think it's appropriate to ship this project with a non-default setting in the spec file.

**Comment by OleHolmNielsen** [comment]
OK, this makes sense.  I agree that the RPM generation is now working correctly.
Will you merge this branch into master then?
IMHO, it would be nice if you could announce the updated version on the slurm-users mailing list, since ```auto_tmpdir``` seems to be the only plugin working reliably at this time.
I wonder if I should write to the list that there is an autofs bug with Slurm's job_containers? Bugs are in
https://bugs.schedmd.com/show_bug.cgi?id=12567 and https://bugs.schedmd.com/show_bug.cgi?id=14344

**Comment by jtfrey** [comment]
Branch merged, release v1.0.1 created.

**Comment by OleHolmNielsen** [comment]
I've built the RPM packages successfully on el7 and el8, thanks a lot!
The CentOS 7.9 has a very old cmake 2.8.12, so I simply loaded our latest EasyBuild module:
```
$ module avail CMake

-------------------------- /home/modules/modules/all ---------------------------
   CMake/3.5.2-foss-2016b        CMake/3.12.1-GCCcore-7.3.0
   CMake/3.6.1-foss-2016b        CMake/3.15.3-GCCcore-8.3.0
   CMake/3.7.2-GCCcore-6.3.0     CMake/3.18.4-GCCcore-10.2.0
   CMake/3.9.1-GCCcore-6.4.0     CMake/3.20.1-GCCcore-10.3.0
   CMake/3.9.5-GCCcore-6.4.0     CMake/3.21.1-GCCcore-11.2.0 (L,D)
   CMake/3.11.4-GCCcore-7.3.0
```

**Comment by OleHolmNielsen** [comment]
Looking at the RPM file, I suggest that a reference to your Github page should be added.
According to https://rpm-packaging-guide.github.io/ there is a SPEC directive called URL which might be added:
```
URL: https://github.com/University-of-Delaware-IT-RCI/auto_tmpdir
```
or perhaps:
```
URL: https://github.com/University-of-Delaware-IT-RCI/%{name}
```
With this line added the URL appears nicely in the RPM file.

**Comment by OleHolmNielsen** [comment]
Maybe you could add the requirement from Changelog.md to the ```Building an RPM section```?  Lots of sites are still running CentOS 7 and would need this instruction:
```
CMake minimum version bumped to 3.6 for CPack (older versions did not work properly under testing)
```
Actually, CentOS 7 provides a CMake 3.17.5 RPM package 
```
yum install cmake3
``` 
where the command provided is ```cmake3``` in stead of  ```cmake```. Maybe you would like to add this hint to README.md?

**Comment by OleHolmNielsen** [comment]
FYI: I have updated my Wiki page instructions on how to install ```auto_tmpdir``` on RPM-based systems:
https://wiki.fysik.dtu.dk/niflheim/Slurm_configuration#temporary-job-directories

**Comment by OleHolmNielsen** [comment]
Slurm seems to have an undocumented requirement that SPANK libraries must be installed on login nodes, in addition to the slurmd nodes of course.  I have reported this as a bug in https://bugs.schedmd.com/show_bug.cgi?id=14483
Whatever the resolution of this issue is going to be, I think it will be valuable to add information to the ```auto_tmpdir``` README.md file.

**Comment by OleHolmNielsen** [comment]
Regarding CMake version 3, it turns out that the command ```cmake3``` can be used on both CentOS 7 (EL7) and RHEL8 clones (EL8).  On EL8 the  ```cmake3``` command is part of the  ```cmake```  RPM package.
So maybe it's simpler to use ```cmake3``` in README.md?

**Comment by jtfrey** [comment]
> Slurm seems to have an undocumented requirement that SPANK libraries must be installed on login nodes, in addition to the slurmd nodes of course. I have reported this as a bug in https://bugs.schedmd.com/show_bug.cgi?id=14483
> Whatever the resolution of this issue is going to be, I think it will be valuable to add information to the `auto_tmpdir` README.md file.

Any plugin you have configured in the `plugstack.conf` on the login node will be loaded by the Slurm utilities.  If that's the case, then you either need to retain the plugin on the login node to satisfy that requirement from the `plugstack.conf` or you need to use an altered `plugstack.conf`.  The `plugstack.conf` can be different on different nodes to effect different plugin behavior as necessary — it is not hashed and checked like the `slurm.conf` file is.

**Comment by jtfrey** [comment]
> Regarding CMake version 3, it turns out that the command `cmake3` can be used on both CentOS 7 (EL7) and RHEL8 clones (EL8). On EL8 the `cmake3` command is part of the `cmake` RPM package.
> So maybe it's simpler to use `cmake3` in README.md?

That is a change made by RHEL for the sake of making two distinct versions of the utility coexist on the PATH.  The same thing is often seen with `python` vs. `python3`.  This is a kludge by the OS and does not reflect default behavior of CMake builds.

**Comment by OleHolmNielsen** [comment]
The inner workings of ```plugstack.conf``` do not seem to be documented.  You're probably right, but I hope this will get reflected in the SPANK documentation.

**Comment by OleHolmNielsen** [comment]
Regarding CMake I agree with you.  A comment in README.md about using ```cmake3``` on RHEL and derivatives would probably be very helpful.
