### ISSUE TITLE
How do I build auto_tmpdir?

### ISSUE THREAD

**Issue by OleHolmNielsen** [University-of-Delaware-IT-RCI/auto_tmpdir#3]
I'd like to test your auto_tmpdir tool, but I'm unable to get started:

Question: How do I build the auto_tmpdir library?  Which are the prerequisite tools?

Thansk,
Ole

**Comment by jtfrey** [comment]
There is a CMakeLists.txt file in the root directory, the necessary build inputs are outlined therein.  Like any Slurm plugin, you'll want to use a similar enough (if not the exact same) compiler toolchain that was used to build Slurm itself.

If I get a chance I'll work on adding an example build of the plugin to the README.md.

**Comment by OleHolmNielsen** [comment]
Thanks!  Only I haven't got a clue how to use CMakeLists.txt to make a build :-(  I was hoping that this would be simple for the author of the code?
