### ISSUE TITLE
AUTO_TMPDIR_ENABLE_SHARED_TMPDIR has 2 table entries in README.md

### ISSUE THREAD

**Issue by OleHolmNielsen** [University-of-Delaware-IT-RCI/auto_tmpdir#7]
The title says it all: The table entry for AUTO_TMPDIR_ENABLE_SHARED_TMPDIR is duplicated with different texts in README.md.

**Comment by jtfrey** [comment]
Addressed in commit 493aa9b400b53bab317b3339ed1069d28fd382df
