### ISSUE TITLE
sudo make install fails on NFS-mounted directory

### ISSUE THREAD

**Issue by OleHolmNielsen** [University-of-Delaware-IT-RCI/auto_tmpdir#8]
When I build  ```auto_tmpdir``` as a normal user and want to ```sudo make install```, errors are found because root doesn't have permission to write files to the user's directory:
```
[ohni@testlogin build-20220629]$ sudo make install
Built target auto_tmpdir
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib64/slurm/auto_tmpdir.so
CMake Error at cmake_install.cmake:77 (file):
  file failed to open for writing (Permission denied):

    /home/niflheim/ohni/auto_tmpdir/build-20220629/install_manifest.txt


make: *** [Makefile:93: install] Error 1
```
I fixed this by cloning the Git repo on a local scratch directory and installing from there.
But I wonder if there exists a more elegant method?

**Comment by jtfrey** [comment]
Your NFS mount probably has [root_squash](https://www.golinuxcloud.com/unix-linux-nfs-mount-options-example/#root_squash_vs_no_root_squash) enabled.

**Comment by OleHolmNielsen** [comment]
NFS root_squash is indeed enabled as a prudent security configuration.
