### ISSUE TITLE
README.md should document that a slurmd restart is required

### ISSUE THREAD

**Issue by OleHolmNielsen** [University-of-Delaware-IT-RCI/auto_tmpdir#9]
When the ```auto_tmpdir.so``` shared library has been installed, and a ```/etc/slurm/plugstack.conf``` configuration file has been created, there is still one missing step which should be documented in ```README.md```:  The slurmd needs to be restarted!

I propose to add a new section at the end of ```README.md```:

Enabling the plugin
--------------------------
The plugin is enabled by adding it to your ```plugstack.conf``` file on all nodes as shown above, for example:
```
required    auto_tmpdir.so          mount=/tmp mount=/var/tmp
```
The ```slurmd``` does not pick up the new plugin until it is restarted:
```
systemctl restart slurmd
```

With each *major version* upgrade to Slurm a new build-<version> directory should be created and a new build done therein.

**Comment by jtfrey** [comment]
See commit 5023822929e495606388f99fa650076251e5a377
